In [4]:
import pandas as pd
df = pd.read_csv("data/orders.csv")
df.head()

,order_id,customer,region,product,category,price,quantity,order_date
0,1001,Anna,Krakow,Laptop,Electronics,3500,1,2026-01-10
1,1002,Piotr,Warsaw,Mouse,Electronics,80,2,2026-01-11
2,1003,Kasia,Krakow,Desk,Furniture,900,1,2026-01-12
3,1004,Tomek,Gdansk,Chair,Furniture,400,4,2026-01-13
4,1005,Magda,Warsaw,Keyboard,Electronics,150,1,2026-01-14

In [31]:
#task 1
df['order_value'] = df['price'] * df['quantity']
df.head(5)

,order_id,customer,region,product,category,price,quantity,order_date,sum,order_value
0,1001,Anna,Krakow,Laptop,Electronics,3500,1,2026-01-10,3500,3500
1,1002,Piotr,Warsaw,Mouse,Electronics,80,2,2026-01-11,160,160
2,1003,Kasia,Krakow,Desk,Furniture,900,1,2026-01-12,900,900
3,1004,Tomek,Gdansk,Chair,Furniture,400,4,2026-01-13,1600,1600
4,1005,Magda,Warsaw,Keyboard,Electronics,150,1,2026-01-14,150,150

In [20]:
#task2
top_region = df.groupby('region')['price'].sum()
top_region

region
Gdansk    1550
Krakow    6095
Warsaw    4930
Name: price, dtype: int64

In [32]:
#task 3
top_category_income = df.groupby('category')['order_value'].sum()
top_category_income

category
Electronics    11285
Furniture       4890
Name: order_value, dtype: int64

In [33]:
#task 4
mean_of_order = df['order_value'].mean()
print(mean_of_order)

1347.9166666666667

In [34]:
#task 5
best_client_revenue = df.groupby('customer')['order_value'].sum().sort_values(ascending = False)
print(best_client_revenue)

customer
Marek     3600
Anna      3500
Bartek    2400
Tomek     1600
Julia     1100
Kamil      950
Kasia      900
Adam       840
Ola        600
Ewa        375
Piotr      160
Magda      150
Name: order_value, dtype: int64