In [2]:
import pandas as pd
df = pd.read_csv("data/orders.csv")
df.head()

,order_id,customer,region,product,category,price,quantity,order_date
0,1001,Anna,Krakow,Laptop,Electronics,3500,1,2026-01-10
1,1002,Piotr,Warsaw,Mouse,Electronics,80,2,2026-01-11
2,1003,Kasia,Krakow,Desk,Furniture,900,1,2026-01-12
3,1004,Tomek,Gdansk,Chair,Furniture,400,4,2026-01-13
4,1005,Magda,Warsaw,Keyboard,Electronics,150,1,2026-01-14

In [3]:
#task 1
df['order_value'] = df['price'] * df['quantity']
df.head(5)

,order_id,customer,region,product,category,price,quantity,order_date,order_value
0,1001,Anna,Krakow,Laptop,Electronics,3500,1,2026-01-10,3500
1,1002,Piotr,Warsaw,Mouse,Electronics,80,2,2026-01-11,160
2,1003,Kasia,Krakow,Desk,Furniture,900,1,2026-01-12,900
3,1004,Tomek,Gdansk,Chair,Furniture,400,4,2026-01-13,1600
4,1005,Magda,Warsaw,Keyboard,Electronics,150,1,2026-01-14,150

In [4]:
#task2
top_region = df.groupby('region')['price'].sum()
top_region

region
Gdansk    1550
Krakow    6095
Warsaw    4930
Name: price, dtype: int64

In [5]:
#task 3
top_category_income = df.groupby('category')['order_value'].sum()
top_category_income

category
Electronics    11285
Furniture       4890
Name: order_value, dtype: int64

In [6]:
#task 4
mean_of_order = df['order_value'].mean()
print(mean_of_order)

1347.9166666666667

In [7]:
#task 5
best_client_revenue = df.groupby('customer')['order_value'].sum().sort_values(ascending = False)
print(best_client_revenue)

customer
Marek     3600
Anna      3500
Bartek    2400
Tomek     1600
Julia     1100
Kamil      950
Kasia      900
Adam       840
Ola        600
Ewa        375
Piotr      160
Magda      150
Name: order_value, dtype: int64

In [10]:
#dzień 2
#task 1
mean_by_region = df.groupby('region')['order_value'].mean()
print(mean_by_region)

region
Gdansk    1050.0
Krakow    1603.0
Warsaw    1252.5
Name: order_value, dtype: float64

In [11]:
print(df.groupby('region').size())

region
Gdansk    3
Krakow    5
Warsaw    4
dtype: int64

In [17]:
#task 2
most_sold_product = df['product'].value_counts()
most_sold_product

product
Laptop      2
Mouse       2
Desk        2
Chair       2
Monitor     2
Keyboard    1
Lamp        1
Name: count, dtype: int64

In [25]:
#task 3
product_values = df.groupby('product')['order_value'].sum().sort_values(ascending = False)
product_values

product
Laptop      7100
Monitor     3500
Chair       2440
Desk        1850
Lamp         600
Mouse        535
Keyboard     150
Name: order_value, dtype: int64

In [38]:
#task 4
worst_revenue_region = df.groupby('region')['order_value'].sum().idxmin()
worst_revenue_region

'Gdansk'

In [40]:
#task 5 only high revenue
expensive_orders = df[df['order_value'] > 2000]
expensive_orders.head()

,order_id,customer,region,product,category,price,quantity,order_date,order_value
0,1001,Anna,Krakow,Laptop,Electronics,3500,1,2026-01-10,3500
5,1006,Bartek,Krakow,Monitor,Electronics,1200,2,2026-01-15,2400
7,1008,Marek,Warsaw,Laptop,Electronics,3600,1,2026-01-17,3600

In [50]:
#task 6
exp_total_revenue = expensive_orders['order_value'].sum()
all_total_revenue = df['order_value'].sum()

print(exp_total_revenue)
print(all_total_revenue)
print(f"Udział wysokich zamowien w porownaniu do wszystkich to {(exp_total_revenue / all_total_revenue * 100).round(2)} %")

9500
16175
Udział wysokich zamowien w porownaniu do wszystkich to 58.73 %